import type { Metadata } from "next";

import { Geist, Geist_Mono } from "next/font/google";

import "@/styles/globals.css";

import Link from "next/link";

import { CartLink } from "@/components/cart-link";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="bg-background min-h-screen">
          <nav className="border-b">
            <div className="container mx-auto flex items-center justify-between px-4 py-4">
              <Link className="text-xl font-bold" href="/">
                React 19 Shop
              </Link>
              <CartLink />
            </div>
          </nav>
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
};

export default RootLayout;
